#!/usr/bi#!/usr/bin/env python3n/env python3
print ("HELLO AND WELCOME TO SUPER CALCULATOR WHAT OPORATION ARE WE USING TODAY")
input ("OPORATION"   )
y = input ("oporation")
if y == int:
    print ("error")
x = int(input("number 1"))
z = int(input("number 2"))
h = input ("conform or deny")
print (y)
print ("THIS IS YOUR OPORATION CONFERM")
input ("conform or deny")
if  input == "Correct" :
    input  ("number one")
    input  ("number two")
if y == "+":
    print ( x + z )
if y == "-":
    print ( x - z )
if y == "*":
    print ( x * z )
if y == "/":
    print ( x / z )



if h : ("deny")
print ("NEW OPORATION.")
b = input ("new oporation")
input ("new oporation is  ")
input  ("number one")
input  ("number two")
    
if b == "+":
    print ( x + z )
if b == "-":
    print ( x - z )
if b == "*":
    print ( x * z )
if b == "/":
    print ( x / z )